# Generated by Django 5.1.7 on 2025-03-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minimal_ecom_base', '0003_product_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='product',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
