# Generated by Django 5.1.7 on 2025-03-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimal_ecom_base', '0004_remove_product_is_visible_product_expire_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_bought_time',
            new_name='bought_time',
        ),
    ]
